services:
  rag-backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev  # nodemon dahil edebilmek için producition için kullanılacak Dockerfile'a alternatif Dockerfile.dev oluşturduk ve içindeki RUN npm ci --only=production yerine RUN npm ci koyduk. Burada da onu dockerfile olarak gösterdik.
    container_name: rag-backend-dev-container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    env_file:
      - ./server/.env
    volumes:
      # Hot reload için kod değişikliklerini izle
      - ./server:/app
      - ./server/uploads:/app/uploads
    command: npm run dev  # nodemon kullanmak için
    restart: unless-stopped
    depends_on:
      - mongodb  # bu satırı unutma amanın
    networks:
      - rag-network
  
  mongodb:
    image: mongo:7
    container_name: rag-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rag_app
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge

volumes:
  mongodb_dev_data: