services:
  rag-backend-dev:
    build:
      context: ./server
      dockerfile: Dockerfile.dev  # nodemon dahil edebilmek için producition için kullanılacak Dockerfile'a alternatif Dockerfile.dev oluşturduk ve içindeki RUN npm ci --only=production yerine RUN npm ci koyduk. Burada da onu dockerfile olarak gösterdik.
    container_name: rag-backend-dev-container
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
    env_file:
      - ./server/.env
    volumes:
      # Hot reload için kod değişikliklerini izle
      - ./server:/app
      - /app/node_modules
    command: npm run dev  # nodemon kullanmak için
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge
