
FROM node:22.19.0-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci # dev dependencies dahil

# Bu sayede uploads dosyasına herkes yazabilecek ve EACCES: permission denided, open 'uploads/tarih_iceren_unique_name.pdf'  // Ayrıca dikkat çekmek isterim ki yml dosyasında volume'da ./server/uploads'ı /app/uploads'a eşledik (./server/uploads:/app/uploads). O yüzden burada da hem app/'i hem de başındaki slash'ı unutma. Yani görüntü şu olacak: /app/uploads
RUN mkdir -p /app/uploads && chmod -R 777 /app/uploads

COPY . .

EXPOSE 5000

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

RUN chown -R nodejs:nodejs /app
USER nodejs


HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD node -e "require('http').get('http://localhost:5000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"

CMD ["npm", "start"]
