
FROM node:22.19.0-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci # dev dependencies dahil

# Dockerfile.dev - RUN npm ci'den sonra ekle:
RUN mkdir -p uploads && chmod 777 uploads

COPY . .

EXPOSE 5000

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

RUN chown -R nodejs:nodejs /app
USER nodejs


HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD node -e "require('http').get('http://localhost:5000/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))"

CMD ["npm", "start"]
